<?php
/**
 *                    Jojo CMS
 *                ================
 *
 * Copyright 2008 Harvey Kane <code@ragepank.com>
 * Copyright 2008 Michael Holt <code@gardyneholt.co.nz>
 *
 * See the enclosed file license.txt for license information (LGPL). If you
 * did not receive this file, see http://www.fsf.org/copyleft/lgpl.html.
 *
 * @author  Harvey Kane <code@ragepank.com>
 * @license http://www.fsf.org/copyleft/lgpl.html GNU Lesser General Public License
 * @link    http://www.jojocms.org JojoCMS
 */

$table = 'cart_country';
$query = "
     CREATE TABLE {cart_country} (
      `countrycode` varchar(2) NOT NULL,
      `name` varchar(255) NOT NULL,
      `region` varchar(255) NOT NULL,
      `defaultregion` varchar(255) NOT NULL,
      `special` enum('yes','no') NOT NULL DEFAULT 'no',
      `applytax` enum('yes','no') NOT NULL DEFAULT 'no',
      `hasstates` enum('yes','no') NOT NULL DEFAULT 'no',
      PRIMARY KEY  (`countrycode`)
    ) ENGINE=MyISAM DEFAULT CHARSET=latin1;";

/* Check table structure */
$result = Jojo::checkTable($table, $query);

/* Output result */
if (isset($result['created'])) {
    echo sprintf("jojo_cart: Table <b>%s</b> Does not exist - created empty table.<br />", $table);
}

if (isset($result['added'])) {
    foreach ($result['added'] as $col => $v) {
        echo sprintf("jojo_cart: Table <b>%s</b> column <b>%s</b> Does not exist - added.<br />", $table, $col);
    }
}

if (isset($result['different'])) Jojo::printTableDifference($table, $result['different']);

/* ensure we have the default regions in there */
$data = Jojo::selectQuery("SELECT * FROM {cart_country}");
if (!count($data)) {
    $defaultcountries = array(
                            array('AF', 'Afghanistan',                    'asia', 'no', 'no', 'no'),
                            array('AL', 'Albania',                        'europe', 'no', 'no', 'no'),
                            array('DZ', 'Algeria',                        'africa', 'no', 'no', 'no'),
                            array('AS', 'American Samoa',                 'oceania', 'no', 'no', 'no'),
                            array('AD', 'Andorra',                        'europe', 'no', 'no', 'no'),
                            array('AO', 'Angola',                         'africa', 'no', 'no', 'no'),
                            array('AI', 'Anguilla',                       'north_america', 'no', 'no', 'no'),
                            array('AQ', 'Antarctica',                     'other', 'no', 'no', 'no'),
                            array('AG', 'Antigua and Barbuda',            'north_america', 'no', 'no', 'no'),
                            array('AR', 'Argentina',                      'south_america', 'no', 'no', 'no'),
                            array('AM', 'Armenia',                        'middle_east', 'no', 'no', 'no'),
                            array('AW', 'Aruba',                          'north_america', 'no', 'no', 'no'),
                            array('AU', 'Australia',                      'oceania', 'no', 'no', 'yes'),
                            array('AT', 'Austria',                        'europe', 'no', 'no', 'no'),
                            array('AZ', 'Azerbaidjan',                    'middle_east', 'no', 'no', 'no'),
                            array('BS', 'Bahamas',                        'north_america', 'no', 'no', 'no'),
                            array('BH', 'Bahrain',                        'middle_east', 'no', 'no', 'no'),
                            array('BD', 'Bangladesh',                     'asia', 'no', 'no', 'no'),
                            array('BB', 'Barbados',                       'north_america', 'no', 'no', 'no'),
                            array('BY', 'Belarus',                        'europe', 'no', 'no', 'no'),
                            array('BE', 'Belgium',                        'europe', 'no', 'no', 'no'),
                            array('BZ', 'Belize',                         'north_america', 'no', 'no', 'no'),
                            array('BJ', 'Benin',                          'africa', 'no', 'no', 'no'),
                            array('BM', 'Bermuda',                        'north_america', 'no', 'no', 'no'),
                            array('BT', 'Bhutan',                         'asia', 'no', 'no', 'no'),
                            array('BO', 'Bolivia',                        'south_america', 'no', 'no', 'no'),
                            array('BA', 'Bosnia-Herzegovina',             'europe', 'no', 'no', 'no'),
                            array('BW', 'Botswana',                       'africa', 'no', 'no', 'no'),
                            array('BV', 'Bouvet Island',                  'other', 'no', 'no', 'no'),
                            array('BR', 'Brazil',                         'south_america', 'no', 'no', 'yes'),
                            array('IO', 'British Indian Ocean Territory', 'other', 'no', 'no', 'no'),
                            array('BN', 'Brunei Darussalam',              'asia', 'no', 'no', 'no'),
                            array('BG', 'Bulgaria',                       'europe', 'no', 'no', 'no'),
                            array('BF', 'Burkina Faso',                   'africa', 'no', 'no', 'no'),
                            array('BI', 'Burundi',                        'africa', 'no', 'no', 'no'),
                            array('KH', 'Cambodia',                       'asia', 'no', 'no', 'no'),
                            array('CM', 'Cameroon',                       'africa', 'no', 'no', 'no'),
                            array('CA', 'Canada',                         'north_america', 'no', 'no', 'yes'),
                            array('CV', 'Cape Verde',                     'africa', 'no', 'no', 'no'),
                            array('KY', 'Cayman Islands',                 'north_america', 'no', 'no', 'no'),
                            array('CF', 'Central African Republic',       'africa', 'no', 'no', 'no'),
                            array('TD', 'Chad',                           'africa', 'no', 'no', 'no'),
                            array('CL', 'Chile',                          'south_america', 'no', 'no', 'no'),
                            array('CN', 'China',                          'asia', 'no', 'no', 'no'),
                            array('CX', 'Christmas Island',               'oceania', 'no', 'no', 'no'),
                            array('CC', 'Cocos (Keeling) Islands',        'oceania', 'no', 'no', 'no'),
                            array('CO', 'Colombia',                       'south_america', 'no', 'no', 'no'),
                            array('KM', 'Comoros',                        'africa', 'no', 'no', 'no'),
                            array('CG', 'Congo',                          'africa', 'no', 'no', 'no'),
                            array('CK', 'Cook Islands',                   'oceania', 'no', 'no', 'no'),
                            array('CR', 'Costa Rica',                     'north_america', 'no', 'no', 'no'),
                            array('HR', 'Croatia',                        'europe', 'no', 'no', 'no'),
                            array('CU', 'Cuba',                           'north_america', 'no', 'no', 'no'),
                            array('CY', 'Cyprus',                         'europe', 'no', 'no', 'no'),
                            array('CZ', 'Czech Republic',                 'europe', 'no', 'no', 'no'),
                            array('DK', 'Denmark',                        'europe', 'no', 'no', 'no'),
                            array('DJ', 'Djibouti',                       'africa', 'no', 'no', 'no'),
                            array('DM', 'Dominica',                       'north_america', 'no', 'no', 'no'),
                            array('DO', 'Dominican Republic',             'north_america', 'no', 'no', 'no'),
                            array('TP', 'East Timor',                     'asia', 'no', 'no', 'no'),
                            array('EC', 'Ecuador',                        'south_america', 'no', 'no', 'no'),
                            array('EG', 'Egypt',                          'africa', 'no', 'no', 'no'),
                            array('SV', 'El Salvador',                    'north_america', 'no', 'no', 'no'),
                            array('GQ', 'Equatorial Guinea',              'africa', 'no', 'no', 'no'),
                            array('ER', 'Eritrea',                        'africa', 'no', 'no', 'no'),
                            array('EE', 'Estonia',                        'europe', 'no', 'no', 'no'),
                            array('ET', 'Ethiopia',                       'africa', 'no', 'no', 'no'),
                            array('FK', 'Falkland Islands',               'south_america', 'no', 'no', 'no'),
                            array('FO', 'Faroe Islands',                  'europe', 'no', 'no', 'no'),
                            array('FJ', 'Fiji',                           'oceania', 'no', 'no', 'no'),
                            array('FI', 'Finland',                        'europe', 'no', 'no', 'no'),
                            array('FR', 'France',                         'europe', 'no', 'no', 'no'),
                            array('FX', 'France (European Territory)',    'europe', 'no', 'no', 'no'),
                            array('GF', 'French Guyana',                  'south_america', 'no', 'no', 'no'),
                            array('TF', 'French Southern Territories',    'other', 'no', 'no', 'no'),
                            array('GA', 'Gabon',                          'africa', 'no', 'no', 'no'),
                            array('GM', 'Gambia',                         'africa', 'no', 'no', 'no'),
                            array('GE', 'Georgia',                        'middle_east', 'no', 'no', 'no'),
                            array('DE', 'Germany',                        'europe', 'no', 'no', 'yes'),
                            array('GH', 'Ghana',                          'africa', 'no', 'no', 'no'),
                            array('GI', 'Gibraltar',                      'europe', 'no', 'no', 'no'),
                            array('GB', 'Great Britain',                  'united_kingdom', 'no', 'no', 'no'),
                            array('GR', 'Greece',                         'europe', 'no', 'no', 'no'),
                            array('GL', 'Greenland',                      'north_america', 'no', 'no', 'no'),
                            array('GD', 'Grenada',                        'north_america', 'no', 'no', 'no'),
                            array('GP', 'Guadeloupe (French)',            'north_america', 'no', 'no', 'no'),
                            array('GU', 'Guam (USA)',                     'oceania', 'no', 'no', 'no'),
                            array('GT', 'Guatemala',                      'north_america', 'no', 'no', 'no'),
                            array('GN', 'Guinea',                         'africa', 'no', 'no', 'no'),
                            array('GW', 'Guinea Bissau',                  'africa', 'no', 'no', 'no'),
                            array('GY', 'Guyana',                         'south_america', 'no', 'no', 'no'),
                            array('HT', 'Haiti',                          'north_america', 'no', 'no', 'no'),
                            array('HM', 'Heard and McDonald Islands',     'other', 'no', 'no', 'no'),
                            array('HN', 'Honduras',                       'north_america', 'no', 'no', 'no'),
                            array('HK', 'Hong Kong',                      'asia', 'no', 'no', 'no'),
                            array('HU', 'Hungary',                        'europe', 'no', 'no', 'no'),
                            array('IS', 'Iceland',                        'europe', 'no', 'no', 'no'),
                            array('IN', 'India',                          'asia', 'no', 'no', 'yes'),
                            array('ID', 'Indonesia',                      'asia', 'no', 'no', 'no'),
                            array('IR', 'Iran',                           'middle_east', 'no', 'no', 'no'),
                            array('IQ', 'Iraq',                           'middle_east', 'no', 'no', 'no'),
                            array('IE', 'Ireland',                        'united_kingdom', 'no', 'no', 'no'),
                            array('IL', 'Israel',                         'middle_east', 'no', 'no', 'no'),
                            array('IT', 'Italy',                          'europe', 'no', 'no', 'no'),
                            array('CI', 'Ivory Coast (Cote DIvoire)',     'africa', 'no', 'no', 'no'),
                            array('JM', 'Jamaica',                        'north_america', 'no', 'no', 'no'),
                            array('JP', 'Japan',                          'asia', 'no', 'no', 'no'),
                            array('JO', 'Jordan',                         'middle_east', 'no', 'no', 'no'),
                            array('KZ', 'Kazakhstan',                     'asia', 'no', 'no', 'no'),
                            array('KE', 'Kenya',                          'africa', 'no', 'no', 'no'),
                            array('KI', 'Kiribati',                       'oceania', 'no', 'no', 'no'),
                            array('KW', 'Kuwait',                         'middle_east', 'no', 'no', 'no'),
                            array('KG', 'Kyrgyzstan',                     'asia', 'no', 'no', 'no'),
                            array('LA', 'Laos',                           'asia', 'no', 'no', 'no'),
                            array('LV', 'Latvia',                         'europe', 'no', 'no', 'no'),
                            array('LB', 'Lebanon',                        'middle_east', 'no', 'no', 'no'),
                            array('LS', 'Lesotho',                        'africa', 'no', 'no', 'no'),
                            array('LR', 'Liberia',                        'africa', 'no', 'no', 'no'),
                            array('LY', 'Libya',                          'africa', 'no', 'no', 'no'),
                            array('LI', 'Liechtenstein',                  'europe', 'no', 'no', 'no'),
                            array('LT', 'Lithuania',                      'europe', 'no', 'no', 'no'),
                            array('LU', 'Luxembourg',                     'europe', 'no', 'no', 'no'),
                            array('MO', 'Macau',                          'asia', 'no', 'no', 'no'),
                            array('MK', 'Macedonia',                      'europe', 'no', 'no', 'no'),
                            array('MG', 'Madagascar',                     'africa', 'no', 'no', 'no'),
                            array('MW', 'Malawi',                         'africa', 'no', 'no', 'no'),
                            array('MY', 'Malaysia',                       'asia', 'no', 'no', 'no'),
                            array('MV', 'Maldives',                       'asia', 'no', 'no', 'no'),
                            array('ML', 'Mali',                           'africa', 'no', 'no', 'no'),
                            array('MT', 'Malta',                          'europe', 'no', 'no', 'no'),
                            array('MH', 'Marshall Islands',               'oceania', 'no', 'no', 'no'),
                            array('MQ', 'Martinique (French)',            'north_america', 'no', 'no', 'no'),
                            array('MR', 'Mauritania',                     'africa', 'no', 'no', 'no'),
                            array('MU', 'Mauritius',                      'africa', 'no', 'no', 'no'),
                            array('YT', 'Mayotte',                        'africa', 'no', 'no', 'no'),
                            array('MX', 'Mexico',                         'north_america', 'no', 'no', 'yes'),
                            array('FM', 'Micronesia',                     'oceania', 'no', 'no', 'no'),
                            array('MD', 'Moldavia',                       'other', 'no', 'no', 'no'),
                            array('MC', 'Monaco',                         'europe', 'no', 'no', 'no'),
                            array('MN', 'Mongolia',                       'asia', 'no', 'no', 'no'),
                            array('MS', 'Montserrat',                     'north_america', 'no', 'no', 'no'),
                            array('MA', 'Morocco',                        'africa', 'no', 'no', 'no'),
                            array('MZ', 'Mozambique',                     'africa', 'no', 'no', 'no'),
                            array('MM', 'Myanmar',                        'asia', 'no', 'no', 'yes'),
                            array('NA', 'Namibia',                        'africa', 'no', 'no', 'no'),
                            array('NR', 'Nauru',                          'oceania', 'no', 'no', 'no'),
                            array('NP', 'Nepal',                          'asia', 'no', 'no', 'no'),
                            array('NL', 'Netherlands',                    'europe', 'no', 'no', 'no'),
                            array('AN', 'Netherlands Antilles',           'north_america', 'no', 'no', 'no'),
                            array('NT', 'Neutral Zone',                   'other', 'no', 'no', 'no'),
                            array('NC', 'New Caledonia (French)',         'oceania', 'no', 'no', 'no'),
                            array('NZ', 'New Zealand',                    'oceania', 'yes', 'yes', 'no'),
                            array('NI', 'Nicaragua',                      'north_america', 'no', 'no', 'no'),
                            array('NE', 'Niger',                          'africa', 'no', 'no', 'no'),
                            array('NG', 'Nigeria',                        'africa', 'no', 'no', 'no'),
                            array('NU', 'Niue',                           'oceania', 'no', 'no', 'no'),
                            array('NF', 'Norfolk Island',                 'oceania', 'no', 'no', 'no'),
                            array('KP', 'North Korea',                    'asia', 'no', 'no', 'no'),
                            array('MP', 'Northern Mariana Islands',       'oceania', 'no', 'no', 'no'),
                            array('NO', 'Norway',                         'europe', 'no', 'no', 'no'),
                            array('OM', 'Oman',                           'middle_east', 'no', 'no', 'no'),
                            array('PK', 'Pakistan',                       'asia', 'no', 'no', 'no'),
                            array('PW', 'Palau',                          'oceania', 'no', 'no', 'no'),
                            array('PA', 'Panama',                         'north_america', 'no', 'no', 'no'),
                            array('PG', 'Papua New Guinea',               'oceania', 'no', 'no', 'no'),
                            array('PY', 'Paraguay',                       'south_america', 'no', 'no', 'no'),
                            array('PE', 'Peru',                           'south_america', 'no', 'no', 'no'),
                            array('PH', 'Philippines',                    'asia', 'no', 'no', 'no'),
                            array('PN', 'Pitcairn Island',                'oceania', 'no', 'no', 'no'),
                            array('PL', 'Poland',                         'europe', 'no', 'no', 'no'),
                            array('PF', 'Polynesia (French)',             'oceania', 'no', 'no', 'no'),
                            array('PT', 'Portugal',                       'europe', 'no', 'no', 'no'),
                            array('PR', 'Puerto Rico',                    'north_america', 'no', 'no', 'no'),
                            array('QA', 'Qatar',                          'middle_east', 'no', 'no', 'no'),
                            array('RE', 'Reunion (French)',               'africa', 'no', 'no', 'no'),
                            array('RO', 'Romania',                        'europe', 'no', 'no', 'no'),
                            array('RU', 'Russian Federation',             'asia', 'no', 'no', 'yes'),
                            array('RW', 'Rwanda',                         'africa', 'no', 'no', 'no'),
                            array('GS', 'S. Georgia & S. Sandwich Isls.', 'other', 'no', 'no', 'no'),
                            array('SH', 'Saint Helena',                   'africa', 'no', 'no', 'no'),
                            array('KN', 'Saint Kitts & Nevis Anguilla',   'north_america', 'no', 'no', 'no'),
                            array('LC', 'Saint Lucia',                    'north_america', 'no', 'no', 'no'),
                            array('PM', 'Saint Pierre and Miquelon',      'north_america', 'no', 'no', 'no'),
                            array('ST', 'Saint Tome (Sao Tome) and Principe', 'africa', 'no', 'no', 'no'),
                            array('VC', 'Saint Vincent & Grenadines',     'north_america', 'no', 'no', 'no'),
                            array('WS', 'Samoa',                          'oceania', 'no', 'no', 'no'),
                            array('SM', 'San Marino',                     'europe', 'no', 'no', 'no'),
                            array('SA', 'Saudi Arabia',                   'middle_east', 'no', 'no', 'no'),
                            array('SN', 'Senegal',                        'africa', 'no', 'no', 'no'),
                            array('SC', 'Seychelles',                     'africa', 'no', 'no', 'no'),
                            array('SL', 'Sierra Leone',                   'africa', 'no', 'no', 'no'),
                            array('SG', 'Singapore',                      'asia', 'no', 'no', 'no'),
                            array('SK', 'Slovak Republic',                'europe', 'no', 'no', 'no'),
                            array('SI', 'Slovenia',                       'europe', 'no', 'no', 'no'),
                            array('SB', 'Solomon Islands',                'oceania', 'no', 'no', 'no'),
                            array('SO', 'Somalia',                        'africa', 'no', 'no', 'no'),
                            array('ZA', 'South Africa',                   'africa', 'no', 'no', 'no'),
                            array('KR', 'South Korea',                    'asia', 'no', 'no', 'no'),
                            array('ES', 'Spain',                          'europe', 'no', 'no', 'no'),
                            array('LK', 'Sri Lanka',                      'asia', 'no', 'no', 'no'),
                            array('SD', 'Sudan',                          'africa', 'no', 'no', 'no'),
                            array('SR', 'Suriname',                       'south_america', 'no', 'no', 'no'),
                            array('SJ', 'Svalbard and Jan Mayen Islands', 'other', 'no', 'no', 'no'),
                            array('SZ', 'Swaziland',                      'africa', 'no', 'no', 'no'),
                            array('SE', 'Sweden',                         'europe', 'no', 'no', 'no'),
                            array('CH', 'Switzerland',                    'europe', 'no', 'no', 'no'),
                            array('SY', 'Syria',                          'middle_east', 'no', 'no', 'no'),
                            array('TJ', 'Tajikistan',                     'asia', 'no', 'no', 'no'),
                            array('TW', 'Taiwan',                         'asia', 'no', 'no', 'no'),
                            array('TZ', 'Tanzania',                       'africa', 'no', 'no', 'no'),
                            array('TH', 'Thailand',                       'asia', 'no', 'no', 'no'),
                            array('TG', 'Togo',                           'africa', 'no', 'no', 'no'),
                            array('TK', 'Tokelau',                        'oceania', 'no', 'no', 'no'),
                            array('TO', 'Tonga',                          'oceania', 'no', 'no', 'no'),
                            array('TT', 'Trinidad and Tobago',            'north_america', 'no', 'no', 'no'),
                            array('TN', 'Tunisia',                        'africa', 'no', 'no', 'no'),
                            array('TR', 'Turkey',                         'middle_east', 'no', 'no', 'no'),
                            array('TM', 'Turkmenistan',                   'asia', 'no', 'no', 'no'),
                            array('TC', 'Turks and Caicos Islands',       'north_america', 'no', 'no', 'no'),
                            array('TV', 'Tuvalu',                         'oceania', 'no', 'no', 'no'),
                            array('UG', 'Uganda',                         'africa', 'no', 'no', 'no'),
                            array('UA', 'Ukraine',                        'asia', 'no', 'no', 'no'),
                            array('AE', 'United Arab Emirates',           'middle_east', 'no', 'no', 'no'),
                            array('US', 'United States of America',       'north_america', 'no', 'no', 'yes'),
                            array('UY', 'Uruguay',                        'south_america', 'no', 'no', 'no'),
                            array('UM', 'USA Minor Outlying Islands',     'north_america', 'no', 'no', 'no'),
                            array('UZ', 'Uzbekistan',                     'asia', 'no', 'no', 'no'),
                            array('VU', 'Vanuatu',                        'oceania', 'no', 'no', 'no'),
                            array('VA', 'Vatican City State',             'europe', 'no', 'no', 'no'),
                            array('VE', 'Venezuela',                      'south_america', 'no', 'no', 'no'),
                            array('VN', 'Vietnam',                        'asia', 'no', 'no', 'no'),
                            array('VG', 'Virgin Islands (British)',       'north_america', 'no', 'no', 'no'),
                            array('VI', 'Virgin Islands (USA)',           'north_america', 'no', 'no', 'no'),
                            array('WF', 'Wallis and Futuna Islands',      'oceania', 'no', 'no', 'no'),
                            array('EH', 'Western Sahara',                 'africa', 'no', 'no', 'no'),
                            array('YE', 'Yemen',                          'middle_east', 'no', 'no', 'no'),
                            array('YU', 'Yugoslavia',                     'europe', 'no', 'no', 'no'),
                            array('ZR', 'Zaire',                          'africa', 'no', 'no', 'no'),
                            array('ZM', 'Zambia',                         'africa', 'no', 'no', 'no'),
                            array('ZW', 'Zimbabwe',                       'africa', 'no', 'no', 'no')
                           );

    for ($i=0; $i<count($defaultcountries); $i++) {
        $defaultcountries[$i][] = $defaultcountries[$i][2];
    }

    foreach ($defaultcountries as $country) {
        Jojo::insertQuery("INSERT INTO {cart_country} SET countrycode=?, name=?, region=?, defaultregion=?, special=?, applytax=?, hasstates=? ", array($country[0], $country[1], $country[2], $country[2], $country[3], $country[4], $country[5]));
    }
}